name: Build Release

on:
  release:
    types: [published]

jobs:
  generate_hashes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Generate hashes.json
        run: |
          python scripts/gen_hashes.py

      - name: Upload hashes.json to existing release
        uses: ncipollo/release-action@v1
        with:
          artifacts: hashes.json
          tag: ${{ github.event.release.tag_name }}
          overwrite: true
